apiVersion: batch/v1
kind: Job
metadata:
  name: reset-load-test-data
  labels:
    app: reset-load-test-data
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      labels:
        app: reset-load-test-data
    spec:
      restartPolicy: Never
      containers:
      - name: reset-load-test-data
        image: nic5694/pe-engineering-hackathon:latest
        imagePullPolicy: Always
        command:
        - uv
        - run
        - python
        - scripts/reset_load_test_data.py
        env:
        - name: DATABASE_NAME
          value: hackathon_db
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USER
          value: postgres
        - name: DATABASE_PASSWORD
          value: postgres